@echo off
REM ****************************************************************************
REM Vivado (TM) v2022.1 (64-bit)
REM
REM Filename    : compile.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for compiling the simulation design source files
REM
<<<<<<< HEAD
REM Generated by Vivado on Mon Oct 24 22:03:54 -0700 2022
REM SW Build 3526262 on Mon Apr 18 15:48:16 MDT 2022
=======
REM Generated by Vivado on Mon Oct 24 20:26:14 -0700 2022
REM SW Build 3247384 on Thu Jun 10 19:36:33 MDT 2021
>>>>>>> 9c8ffcce526d4a22c6a071ade99b7f82d69be976
REM
REM IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
REM
REM usage: compile.bat
REM
REM ****************************************************************************
REM compile Verilog/System Verilog design sources
<<<<<<< HEAD
echo "xvlog --incr --relax -L uvm -prj ALU_decoder_tb_vlog.prj"
call xvlog  --incr --relax -L uvm -prj ALU_decoder_tb_vlog.prj -log xvlog.log
=======
echo "xvlog --incr --relax -L uvm -prj tb_datapath_vlog.prj"
call xvlog  --incr --relax -L uvm -prj tb_datapath_vlog.prj -log xvlog.log
>>>>>>> 9c8ffcce526d4a22c6a071ade99b7f82d69be976
call type xvlog.log > compile.log
if "%errorlevel%"=="1" goto END
if "%errorlevel%"=="0" goto SUCCESS
:END
exit 1
:SUCCESS
exit 0
