@echo off
REM ****************************************************************************
REM Vivado (TM) v2022.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
<<<<<<< HEAD
REM Generated by Vivado on Mon Oct 24 22:03:56 -0700 2022
REM SW Build 3526262 on Mon Apr 18 15:48:16 MDT 2022
=======
REM Generated by Vivado on Mon Oct 24 20:26:15 -0700 2022
REM SW Build 3247384 on Thu Jun 10 19:36:33 MDT 2021
>>>>>>> 9c8ffcce526d4a22c6a071ade99b7f82d69be976
REM
REM IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
REM elaborate design
<<<<<<< HEAD
echo "xelab --incr --debug typical --relax --mt 2 -L xil_defaultlib -L uvm -L unisims_ver -L unimacro_ver -L secureip --snapshot ALU_decoder_tb_behav xil_defaultlib.ALU_decoder_tb xil_defaultlib.glbl -log elaborate.log"
call xelab  --incr --debug typical --relax --mt 2 -L xil_defaultlib -L uvm -L unisims_ver -L unimacro_ver -L secureip --snapshot ALU_decoder_tb_behav xil_defaultlib.ALU_decoder_tb xil_defaultlib.glbl -log elaborate.log
=======
echo "xelab -wto df0b0ef311064cb08a34cc130889ab8d --incr --debug typical --relax --mt 2 -L xil_defaultlib -L uvm -L unisims_ver -L unimacro_ver -L secureip --snapshot tb_datapath_behav xil_defaultlib.tb_datapath xil_defaultlib.glbl -log elaborate.log"
call xelab  -wto df0b0ef311064cb08a34cc130889ab8d --incr --debug typical --relax --mt 2 -L xil_defaultlib -L uvm -L unisims_ver -L unimacro_ver -L secureip --snapshot tb_datapath_behav xil_defaultlib.tb_datapath xil_defaultlib.glbl -log elaborate.log
>>>>>>> 9c8ffcce526d4a22c6a071ade99b7f82d69be976
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
