@echo off
REM ****************************************************************************
REM Vivado (TM) v2022.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
<<<<<<< HEAD
REM Generated by Vivado on Mon Oct 24 22:03:59 -0700 2022
REM SW Build 3526262 on Mon Apr 18 15:48:16 MDT 2022
=======
REM Generated by Vivado on Mon Oct 24 20:26:17 -0700 2022
REM SW Build 3247384 on Thu Jun 10 19:36:33 MDT 2021
>>>>>>> 9c8ffcce526d4a22c6a071ade99b7f82d69be976
REM
REM IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
<<<<<<< HEAD
echo "xsim ALU_decoder_tb_behav -key {Behavioral:sim_1:Functional:ALU_decoder_tb} -tclbatch ALU_decoder_tb.tcl -log simulate.log"
call xsim  ALU_decoder_tb_behav -key {Behavioral:sim_1:Functional:ALU_decoder_tb} -tclbatch ALU_decoder_tb.tcl -log simulate.log
=======
echo "xsim tb_datapath_behav -key {Behavioral:sim_1:Functional:tb_datapath} -tclbatch tb_datapath.tcl -log simulate.log"
call xsim  tb_datapath_behav -key {Behavioral:sim_1:Functional:tb_datapath} -tclbatch tb_datapath.tcl -log simulate.log
>>>>>>> 9c8ffcce526d4a22c6a071ade99b7f82d69be976
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
